// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC65uzrsFzfrsNpfN3SVTb3zQB0cp67GZc',
    appId: '1:70358305534:android:d6b7a9645dbd74237fb3af',
    messagingSenderId: '70358305534',
    projectId: 'apptravelmaqdis',
    storageBucket: 'apptravelmaqdis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVb0WLp0jud31M26pFcTAZW8_Qep3o4pM',
    appId: '1:70358305534:ios:e2fe0f261b8e85867fb3af',
    messagingSenderId: '70358305534',
    projectId: 'apptravelmaqdis',
    storageBucket: 'apptravelmaqdis.firebasestorage.app',
    androidClientId: '70358305534-ieaohocv14a7rvlrhjjefcv4bqoetp08.apps.googleusercontent.com',
    iosClientId: '70358305534-1kfpgo5ahsvhh3dpvk3emgp29d4hika1.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

}